azure-pipelines.yml
This PR updates the macOS VM on Azure from 10.13 to 10.15.  Also added a newline to the end of the Azure YAML file.
The obs-studio repo is currently using 10.15 on Azure, so this change brings this repo in line with the obs-studio repo.
I have not tested this.
- CI update
=> Update Azure macOS VM to 10.15

build-package-deps-osx.sh, osx-install-tools.sh
Update macOS dependencies
* Update Opus from 1.2.1 to 1.3.1
* ~~Update libogg from 1.3.3 to 1.3.4~~
* Update libvpx from 1.7.0 to 1.8.2
* Update Jansson from 2.11 to 2.12
* Update FFmpeg from 4.0.2 to 4.2.2
* Update x264 git repo location
This brings macOS in line with the [current Windows release dependencies](https://github.com/obsproject/obs-studio/wiki/Release-Dependency-Versions/2da5ee806df52234a834499f77e8b722f5adcac5) for Opus, libogg, and FFmpeg.  The Windows deps use libvpx 1.8.1, but 1.8.2 is currently the latest release.  It looks like the obs-studio repo bundles Jansson 2.9, but the macOS CI scripts were already using Jansson 2.11, so I've updated to Jansson 2.12.  I'm open to adjusting libvpx and Jansson versions to something else.
I have only tested that the links for the …
=> Update macOS dependencies

build-package-deps-osx.sh
=> Build freetype

Brewfile, osx-install-tools.sh
Homebrew bundle is the suggested tool to manage and bundle Homebrew dependencies. It automatically re-uses existing packages and installs required ones. Due to its design it can even unlink existing packages and side-load pinned formulas, all defined in a single Brewfile.
Fixes issues with different Homebrew environments as it installs and updates formulas as necessary, so no fallback code in CI scripts is needed.
This also avoids CI scripts failing their workflows due to Homebrew returning with error when either a) an installed package is tried to be installed again or b) a package that needs to be unlinked isn't installed in the first place.
* Tested locally
* Tested with CI runs
=> Use Homebrew bundle to install missing brew dependencies

.github/workflows/build_deps.yml
This builds luajit from the git mirror's current HEAD of the 2.1 branch.
In older luajit versions the linker needs some flags that break m1 macOS machines complicating the process. This newer version doesn't need those flags so the build process is the same for both platforms.
Ran in CI
=> Set luajit to current 2.1 commit

LICENSE
Adds license file for obs-deps.
Explicitly state permissions for repository source code.
* No testing necessary
- Documentation (a change to documentation pages)
=> Add LICENSE file for obs-deps

CI/include/build_support.sh
Git requires a user to be set up before certain operations will work (e.g., cherry-pick).
The `git cherry-pick` operation requires that a git user (user.email and user.name) be set up.  If one is not set up (like on CI), let's set one up to use.
`git config --get` will produce an error if the key cannot be found or it is not set, so I have temporarily `set +e` around these calls.  If there is a preferred alternative, such as appending ` || true` to the calls, let me know.
I want to be able to use `git cherry-pick`.
Tested locally on Ubuntu.
=> Add function to check git config

.gitattributes
Prevent EOL conversions for licenses
License files should probably be committed as-is without trying to force the EOL marker to adhere to any particular format.  This change to `.gitattributes` should exclude all files in all sub-folders of `/licenses` from all end-of-line conversion.[1]
[1]: https://git-scm.com/docs/gitattributes#_text
Prevent unnecessary changes to license files.
=> Prevent EOL conversions for licenses

CI/include/build_support.sh
This commit adds support for a component build script to pass the "set \<sparse-path>" string to github_fetch via _build_setup_git.
Sparse checkouts can drastically reduce the space necessary to checkout a repository if we only need to clone specific parts of the repository.
Includes #71 because the changes were too close together to commit wholly separately.
Have used locally and on GHA while testing the Windows deps branch.
=> Add support for git sparse-checkout

CI/include/build_support.sh
To add support for git sparse-checkout, I had tried to change github_fetch to allow it to accept three OR four arguments. Instead of causing it to error out if less than three arguments were supplied, I'd caused it to error out if three or less arguments weere supplied. This is because I'd used the -le operator (less than or equal to) instead of the -lt operator (less than). Use the correct -le operator here. 
Fix builds.
Tested the comparison operator change in local test scripts.
=> Fix github_fetch argument count check

.github/workflows/windows_deps.yml
Use the appropriately prefixed tag name. Make release name specify "Windows" in the title.
Would be nice to not create a duplicate tag. Would be helpful to distinguish the Windows releases from the macOS releases.
=> Fix Windows releases

.github/workflows/windows_deps.yml, CI/build-deps-windows-native.ps1, CI/windows/build_ntv2.ps1
Add the AJA NTV2 library to Windows deps.  This is the Windows companion to #82.
Want to easily support Windows builds with the Aja plugin.
I've only done local build tests for this dependency.  I haven't tested the resulting files against an OBS build, and I don't have any AJA hardware to test with.
=> Add AJA NTV2 library to Windows deps

.github/workflows/windows_deps.yml, CI/windows/build_ffmpeg.sh
This change instructs the ffmpeg build script to exclude Media Foundation as a dependency, thru `--disable-mediafoundation`
A few versions back we bumped FFMPEG to a version that enables Media Foundation by default. I dont believe we need to rely on Media Foundation for the time being.
For Windows 10/11 "N" versions, which ships without Media Foundation installed, it will completely prevent the user from running OBS Studio.
A fairly large number of users run Windows N are coming by the support channels asking for help.
Manually installing Media Foundation can be quite confusing and difficult for a lot of users.
Built the modified FFMPEG thru our build scripts.
Verified that the avcodec-58.dll no longer depends on mfplat.dll.
Dropped the avcodec-58.dll into a release OBS, on Windows 10 N …
=> FFmpeg: Remove Media Foundation dependency

.github/workflows/windows_deps.yml, CI/windows/build_mbedtls.sh
This patch was causing encrypted SRT connections (such as to Cloudflare) to fail to establish a successful connection during the handshake. This threading patch/config change was only meant to be used in the native-compiled static build of mbedTLS. Removing this change from the cross-compiled build resolves the issue.
This will need a cache revision change, but I will do that later as there is another pending PR for Windows deps.
Want encrypted SRT to work.
Build obs-deps and built obs-studio locally. Tested encrypted SRT connection. Connection worked after these changes.
=> Fix broken encrypted SRT connections

utils.pwsh/Invoke-DevShell.ps1, utils.pwsh/Invoke-External.ps1, utils.pwsh/Invoke-GitCheckout.ps1, utils.pwsh/Invoke-SafeWebRequest.ps1
Fix Logger utility include.
Per @PatTheMav 's [comment](https://github.com/obsproject/obs-deps/pull/108/files#r884806737) in #108, the correct filename is "Logger.ps1". Let's just fix it everywhere and keep PR scopes narrow.
Visually inspected the changes.
=> Fix Logger utility include

utils.pwsh/Check-GitUser.ps1
Add a utility to check if a repo has a git user configured. If not, configure one so that git can commit patches.
Helps us handle cases where we need to commit a patch to prevent a repo from being considered dirty, which causes some build tools to error out.
Tested locally on Windows 10 in PowerShell 7.2.4.
=> utils.pwsh: Add Check-GitUser

.github/actions/build-ffmpeg/action.yml, .github/actions/build-macos-deps/action.yml, .github/actions/build-macos-qt/action.yml, .github/actions/build-windows-deps/action.yml, .github/actions/create-single-arch/action.yml, .github/actions/create-universal/action.yml, .github/workflows/main.yml
Update first-party GitHub Actions.
Keep first-party Actions up to date with the current major release.
The PR is the test.
=> CI: Update first-party GitHub Actions

deps.windows/40-detours.ps1
This reverts commit c2da6606dcb4d43b6d2337dbd06f2ab19a16d1ad.
We don't want to update Detours to an untagged commit.
We want game capture to remain predictable and stable, so we'd prefer stable tags of Detours.
We used this before.
=> Revert "deps.windows: Update Detours to 24357c6a5a"

deps.ffmpeg/30-svt-av1.zsh
The GitHub repo is no longer available
https://github.com/AOMediaCodec/SVT-AV1
Fix obs-deps scripts
I work on adding ADS and my CI seems to work again with this.
=> deps.ffmpeg: Use SVT-AV1 GitLab repo

deps.windows/60-zstd.ps1, licenses/zstd/COPYING, licenses/zstd/LICENSE
Add static build of zstd for https://github.com/obsproject/obs-studio/pull/8074
Want to make the world better.
Built locally, built OBS PR with built zstd.
=> deps.windows: Add Zstandard

deps.ffmpeg/80-amf.zsh
Update AMF to version 1.4.29 to make https://github.com/obsproject/obs-studio/pull/6927 works.
Difference between upstream and "external" from OBS Studio repo:
- "external" have outdated code compared to 1.4.28 from upstream
- This [enum value](https://github.com/obsproject/obs-studio/blob/48b5fd5a3ba115b4bf9dc84c17d28d8febfd9e99/plugins/obs-ffmpeg/external/AMF/include/components/HQScaler.h#L48) that is not present upstream and is unused in OBS Studio whole repo (the header itself is not used), so it's removal is seamless.
How ?:
I pasted 1.4.28 over our "external" version and each diff (except the enum value) happen to be new code because if I blame upstream code and check the prior code, the prior code match "external".
And `AMF_HQ_SCALER_ALGORITHM_FSR1_1` looks completely unused when I …
=> deps.ffmpeg: Update AMF to 1.4.29

deps.windows/30-speexdsp.ps1, deps.windows/patches/speexdsp/0001-Add-CMakeLists.patch
Interprocedural Optimization (INTERPROCEDURAL_OPTIMIZATION / IPO) is interpreted by CMake as Link-time code generation (LTCG). This causes build problems on Windows when Visual Studio versions mismatch, so let's remove it.
Want less problems building. Change recommended by @notr1ch.
I have not tested this.
=> deps.windows: Disable IPO in SpeexDSP build

deps.ffmpeg/60-mbedtls.zsh
This reverts commit a050e86d64cace723849b68afeba35d4b3637353.
Revert mbedTLS to 3.2.1 to avoid an issue with Designated Initializers when compiling against mbedTLS headers from a C++ program.
Want to avoid build problems. Will revisit for a future release.
We were on mbedTLS 3.2.1 previously, so it has been tested before.
=> Revert "deps.ffmpeg: Update mbedTLS to 3.3.0"

licenses/libdatachannel/LICENSE, licenses/libdatachannel/libjuice/LICENSE, licenses/libdatachannel/libsrtp/LICENSE, licenses/libdatachannel/nlohmann-json/LICENSE.MIT, licenses/libdatachannel/plog/LICENSE, licenses/libdatachannel/usrsctp/LICENSE.md
Correct an oversight from the PR that added libdatachannel (#170). The license file was not added then, so let's add it now.
Want component licenses properly documented.
n/a
- Documentation (a change to documentation pages)
=> deps.ffmpeg: Add libdatachannel licenses

.github/workflows/main.yaml
CI: Update Ubuntu runners to 22.04
This updates the Ubuntu runners used for the Linux/Ubuntu FFmpeg test job and also the Windows FFmpeg cross-compilation jobs. Incidentally, this might also fix the current CI failures caused by nasm.us being down, since 22.04 has a newer version of nasm available (2.15.05 on Ubuntu 22.04 versus 2.14.02 on Ubuntu 20.04).
Want the runners to use the minimum version of Ubuntu we support. Don't want CI to fail.
It has not been tested.
=> CI: Update Ubuntu runners to 22.04

.github/workflows/main.yaml
The Action softprops/action-gh-release is currently emitting warnings about using node12 and set-output. We're currently using v0.1.14. Updating to v0.1.15 should resolve these warnings.
Don't want warnings on CI.
It seems like the v0.1.14 tag may be from a deleted branch, but the second commit here on the master branch seems identical.
https://github.com/softprops/action-gh-release/commit/1e07f4398721186383de40550babbdf2b84acfc5
https://github.com/softprops/action-gh-release/commit/17cd0d34deddf848fc0e7d9be5202c148c270a0a
Either of these comparisons should be a good representation of the diff, but I've given both due to the oddity of the v0.1.14 tag.
https://github.com/softprops/action-gh-release/compare/v0.1.14...v0.1.15
https://github.com/softprops/action-gh-release/compare/17cd0d34dedd …
=> CI: Update GitHub Actions to remove warnings

deps.windows/30-curl.ps1
deps.windows: Update curl to 8.4.0
Update to address CVE-2023-38545.
I haven't tested this. Will see if CI is green.
=> deps.windows: Update curl to 8.4.0

.github/workflows/main.yaml
The softprops/action-gh-release action is the last remaining action in this repo that was still using node16. Updating should remove the associated warnings.
Want less CI warnings so the meaningful warnings stand out.
Tested on my fork with obs-plugintemplate and got CI to be green with no warnings about node16.
See:
* https://github.com/obsproject/obs-plugintemplate/pull/118
=> CI: Update softprops/action-gh-release to v2.0.4

.github/actions/package-windows-qt/action.yaml
We avoid shipping the Qt binary tool PDBs because we haven't had a need for them.
Qt 6.5 added the tracepointgen tool. Let's exclude that.
Somewhere between Qt 6.5.3 and 6.6.1, the syncqt tool started building PDBs even in Release configuration. Let's just exclude it for now. We can unravel that mystery another day.
Want smaller deps packages. The PDBs will still be included in the PDBs zip and Debug zip if someone needs them.
Noticed this while doing local deps builds.
I haven't tested this. If needed, I can do a test run on Windows later. This seems pretty straightforward though.
=> CI: Remove additional Qt PDBs

deps.windows/70-vpl.ps1
Updating VPL to the most recent version v2.12.0 for current and future PRs. 
Update is needed for https://github.com/obsproject/obs-studio/pull/10902/files. 
- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are properly formatted and commits squashed where appropriate.
- [ x] I have included updates to all appropriate documentation.
=> deps.windows: Update VPL to v2.12.0

deps.qt/checksums/qtbase-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qtbase-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qtbase-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/checksums/qtimageformats-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qtimageformats-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qtimageformats-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/checksums/qtmultimedia-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qtmultimedia-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qtmultimedia-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/checksums/qtshadertools-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qtshadertools-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qtshadertools-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/checksums/qtsvg-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qtsvg-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qtsvg-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/checksums/qttools-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qttools-everywhere-src-6.6.3.zip.sha256, deps.qt/checksums/qttools-everywhere-src-6.7.2.tar.xz.sha256, deps.qt/qt6.ps1, deps.qt/qt6.zsh
Revert the Qt 6.7 update which updated from Qt 6.6.3 to 6.7.2.
Due to issues on Windows 11, revert this update for now. See:
* https://bugreports.qt.io/browse/QTBUG-128517
* https://bugreports.qt.io/browse/QTBUG-128518
Qt 6.6.3 has been used in previous OBS Studio releases.
=> Revert Qt 6.7 update

deps.ffmpeg/80-amf.ps1, deps.ffmpeg/80-amf.zsh
- Update AMF to 1.4.36 and include AV1 B-frame interface
- Include the latest AMF interface changes and AV1 B-frame support
- Tested on Navi31 and Navi48
- AV1 B-frames working with this + https://github.com/obsproject/obs-studio/pull/11521
=> deps.ffmpeg: Update AMF to 1.4.36

deps.windows/70-vpl.ps1
Updating VPL to the most recent version v2.14.0 for current and future PRs.
Update is needed for https://github.com/obsproject/obs-studio/pull/11460
- Tweak (non-breaking change to improve existing functionality) -->
- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are properly formatted and commits squashed where appropriate.
- [ x] I have included updates to all appropriate documentation.
=> deps.windows: Update VPL to v2.14.0

.github/workflows/main.yaml, .github/workflows/scheduled.yaml
Update Ubuntu runners to 24.04.
Keep the runners up to date.
It hasn't.
=> CI: Update Ubuntu runners to 24.04

utils.pwsh/Install-BuildDependencies.ps1
utils.pwsh: Add debug logging in Install-BuildDependencies
While checking another issue, it was helpful to have additional debug logging.
If the reflection to get the function name does not make sense for the added complexity, I could replace it with a simple string prefix, which is what we do elsewhere.
https://github.com/obsproject/obs-deps/blob/006b94d8e1e4707c85edae99d8db25e1fc7a4f61/utils.pwsh/Invoke-External.ps1#L30
Tested locally on Windows 11 in PowerShell 7.4.6.
=> utils.pwsh: Add debug logging in Install-BuildDependencies

.github/workflows/scheduled.yaml
Adds the Qt6 Windows on Arm native builds to the scheduled workflow so that caches are generated.
This was missed when enabling the Qt6 Windows on Arm native builds.
It hasn't, but the syntax is directly copied from the YAML in main.yaml.
=> CI: Add Qt6 Windows Arm builds to the scheduled workflow
