obsproject/obs-deps

build-package-deps-osx.sh
Update x264 git repo location.
The x264 git repo location has changed.  Without updating it here, the build will fail with:
```
Cloning into 'x264'...
fatal: remote error: access denied or repository not exported: /x264.git
```
I made sure my fork's pipeline can build.
=> Update x264 git repo location

build-package-deps-osx.sh
* Adds srt as a static library for ffmpeg
* Adds mbedtls as a dynamic library for ffmpeg and OBS
* Add code to correct library paths inside `dylibs` to assist OBS' packaging process for macOS
* Brings srt support to OBS 25 on macOS
* Tested on macOS 10.15.4 with packaged as well as unpackaged OBS builds
* SRT output tested with streaming as well as ffmpeg output using local SRT server
* SRT server output tested with `ffplay` to check video stream
=> Add srt and mbedtls support to FFmpeg

.github/workflows/build_macos.yml
Adds necessary GitHub action workflow files to replicate functionality of current Azure pipeline.
Remove dependency on external system and keep CI within GitHub.
* Build functionality tested on own fork
=> Add GitHub action for macOS builds

build-package-deps-osx.sh
Rewrite of the macOS build script to allow configuration of required modules (and their versions) at the top of the file and split build processes into separate shell functions.
Eases maintenance of the build script and for the most part allows updating versions by changing a version number at the top of the file.
* Tested locally on MacOS 10.15.4 
* Tested via GitHub action
* Integrated and tested with packaged and unpackaged OBS
- Code cleanup (non-breaking change which makes code smaller or more readable) -->
=> Make obsdeps modular and configurable

build-package-deps-osx.sh
Fixes bad directory references in mbedtls' `dylib`s after building. 
When mbedtls builds its dynamic libraries, their ID and paths are set to the temporary build folder used by the build script. The script fixes these after copying them into the final directory, but the destination folders were incorrectly set. This CR fixes the issue.
* OBS successfully built and tested with updated obs-deps artifact from GitHub Actions.
=> Fix mbedtls directory references

build-package-deps-osx.sh
Change mbedtls source code download to use GPL-licensed version.
Align license use with OBS Studio.
* Successfully compiled locally and on CI
=> Change to GPL version of mbedtls release

build-package-deps-osx.sh
=> Some freetype fixes

.github/workflows/build_macos.yml
Uses newer version of upload-artifact action and additional workflow step to properly name generated artifacts.
Fixes an oversight in the original GitHub Actions workflow.
Artifacts are only created on push, so not fully tested.
=> Update workflow to use newer upload-artifact action with proper names

build-package-deps-osx.sh
Updates luajit to version 2.1.0-beta3 to fix possible issues with 64-bit environments (mainly macOS Catalina). Usage of 2.1.0 under Catalina is also suggested by the developers themselves: https://github.com/LuaJIT/LuaJIT/issues/521
Possibly fixes https://github.com/obsproject/obs-studio/issues/2784
* Dependencies compiled locally
* OBS built with the dependencies
* LUA scripts tested in OBS
=> Update luajit to 2.1.0-beta3 to fix possible 64-bit issues

build-package-deps-osx.sh
Xiph has migrated a few of their repositories to GitLab recently and git.xiph.org seems to have been down for a while. Let's change this download to their GitLab instance so it stops failing.
Unfortunately, because of how GitLab packages the download and refers to the commit, I had to pass the full commit hash in BUILD_PACKAGES instead of the short hash.
https://gitlab.xiph.org/xiph/opus/-/merge_requests/2
CI failing is sad.
I let this run on my Azure Pipeline to make sure that it builds.
=> Change libogg download from git.xiph.org to gitlab.xiph.org

.github/workflows/build_deps.yml
This PR fixes two bugs introduced by the last PR and adds some optimizations:
* Ensure Qt is built without glib support (which is not needed for macOS anyway)
* Ensure that LuaJIT is built in `/tmp/obsdeps` to ensure correct dylib identity and paths
* Add `-PR` option to copies to keep versioned symlinks intact
As CI containers have additional optional dependencies installed that OBS doesn't need, pre-built libraries will be linked to these optional dependencies. Downloading and building with them will fail if the same dependencies are not installed on local machines as well.
As these optional dependencies (in this case `glib`) are not needed, the Qt build configuration needs to be amended to explicitly disable this.
The LuaJIT changes are necessary as we require all `dylib`s to be linked …
=> CI: Fix unnecessary glib dependency in Qt build

.github/workflows/build_deps.yml, build_script_generator.py, osx-install-tools.sh, templates/build-script-macos.tpl, templates/build-script-ubuntu.tpl
Hides `webp` and `libtiff` from Qt by unlinking them if installed via Homebrew, forcing Qt to use self-provided third party source code to compile both dependencies statically into its frameworks.
_Bonus Level:_ The provided build script generator was committing unusable scripts back into the repository, as an absolute checkout folder was used for script generation. The PR changes this to use the dynamically detected git checkout directory instead.
Qt requires the `imageformats` plugin by default, which itself has dynamic libraries for tiff and webp support. If neither library is available on the system, their respective libraries are compiled into the Qt plugin library with the source code Qt provides themselves.
On CI and some local machines both these libraries might exist already …
=> CI: Fix Qt building imageformats plugin with Homebrew-provided deps

README.md
Update README for macOS to use correct order of events for building deps, then using deps to build OBS.
Fixes https://github.com/obsproject/obs-deps/issues/20
* Readme markdown previewed locally 
- Documentation (a change to documentation pages)
=> Update README.MD for macOS

.github/workflows/build_deps.yml
Adds `rnnoise` pre-built library for macOS.
Necessary for feature-parity with Windows version of OBS.
* Dependencies built locally
* OBS compiled with new dependencies
* Rnnoise available for noise canceling in filter UI
=> CI: Add rnnoise dependency for macOS

.github/workflows/build_deps.yml
Fixes x264 failing on CI for macOS due to a cache directory mismatch.
Restore macOS builds finishing.
* Needs to be tested on CI
=> CI: Fix x264 failing to build because of cache directory mismatch

.github/workflows/build_deps.yml, build_script_generator.py
Changes usage of `set-env` in GitHub Actions with the new syntax to set environment variables for later steps.
Github deprecates the `set-env` command: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* Needs to be tested on CI
=> CI: Remove deprecated usage of `set-env` in Github Actions workflow

.github/workflows/build_deps.yml
Fixes caching of Qt build results.
To avoid additional pre-existing Qt dependencies to be linked when building for distribution, `zstd` is unlinked before building Qt. Unfortunately `zstd` is required by the Github caching actions.
Linking `zstd` after successfully building Qt will restore caching functionality.
* Tested in my own fork
=> CI: Fix caching for Qt builds on macOS

build_script_generator.py, templates/build-script-macos.tpl
This update adds an additional function to restore homebrew formulas once the script finishes. When building locally, certain pre-existing formulas need to be unlinked to avoid the deps being linked against them. Once the script is done, the original system state should be restored.
Reduce friction/impact of local build scripts on system configurations.
* Tested locally
=> Update build scripts for macOS to restore homebrew env after building

.github/workflows/build_deps.yml, .github/workflows/create_scripts.yml, utils/build_script_generator.py
Fixes unexpected dependency on brotli introduced by freetype's support for WOFF fonts. This lead to brotli being linked from Homebrew inside the deps artifact which cannot be found when bundling OBS.
Also introduces "stable" function naming in the build scripts. The script generator workflow was diffing old and new scripts and as a `uuid` was used _any_ invocation of the script generated a diff and the generator ran even though it didn't have to (this also generates unnecessary script generation runs on forks which makes rebasing a pain).
Enables building/bundling of OBS without missing dependencies.
* Freetype building tested locally (confirmed brotli was excluded)
* Python script generator tested
=> CI: Fix brotli dependency on freetype

azure-pipelines.yml
Updates azure pipelines workflows for macOS to use scripts generated from Github CI workflows. This allows Azure to always stay up to date with Github's workflow.
Remove burden to update two workflows at the same time and also keeps dependencies built on azure updated.
Needs to be tested on Azure CI directly.
=> CI: Update azure pipelines to use auto-generated scripts

.github/workflows/build_deps.yml
Adds liblamemp3 to ffmpeg as static dependency and simplifies ffmpeg dependency cache management (all dependencies are contained in a single cache now).
Support for lame-mp3 came up in a PR on the main project (https://github.com/obsproject/obs-studio/pull/3708), this PR implements the functionality.
* Generated scripts ran locally, all dependencies built successfully
=> CI: Add liblamemp3 to ffmpeg

.github/workflows/build_deps.yml
Update x264 to newest release.
Since x264 has moved their stack realignment from asm to C, an additional workaround for High Sierra (10.13) is needed as its clang is too old to support this feature.
See also: https://code.videolan.org/videolan/x264/-/commit/b5bc5d69c580429ff716bafcd43655e855c31b02
* x264 built locally
=> CI: Update x264 with new stack realignment

.github/workflows/build_deps.yml
Updates Qt to 5.15.2 as part of prebuilt dependencies.
Prepares for milestone 26.1 as discussed in https://github.com/obsproject/obs-studio/issues/3752.
* Qt built locally
* OBS built with most recent deps and Qt
* OBS launched
* Checked VirtualCamera
* Checked Recording
* Checked Streaming (local SRT server)
=> CI: Update to Qt 5.15.2 for macOS

.github/workflows/build_deps.yml
Downgrades `FFmpeg` and `srt` to last known "good" versions for HLS streaming.
Current stable FFmpeg available on macOS (v4.3.1) has introduced changes breaking HLS streaming. Version 4.2.3 is the last known "good" version also vetted by Homebrew, so we downgrade to this version. This downgrade also makes downgrading `srt` necessary, but has the positive side-effect of not requiring us to patch `ffmpeg`.
Build and tested locally, HLS stream works properly with these versions. SRT streaming (at least locally) also still worked.
=> CI: Downgrade ffmpeg version on macOS to fix HLS streaming issue

.github/workflows/build_deps.yml
Fixes `lame-mp3` using a dependency symbol only available on macOS 10.14+.
For some reason `lame-mp3` doesn't recognise the `MACOSX_DEPLOYMENT_TARGET` environment variable set by the workflow and requires it to be set explicitly when invoking `make`.
*Note:* This might mean that setting it globally doesn't work or it could just mean that lame's build process doesn't pick it up correctly. We should be on the lookout for more incompatibilities.
Dependencies were built locally and checked to not contain the offending `____chkstk_darwin` symbol.
=> CI: Fix incompatibilities with macOS 10.13

.github/workflows/build_deps.yml
Makes FFmpeg properly re-build itself when a dependency revision takes place.
FFmpeg did not take dependency revision into account when evaluating its cache (as only dependency versions, but not revisions where part of the hash). Now the revision is part of the hash and should properly lead to a cache miss.
Needs to be tested on CI.
=> CI: Fix ffmpeg not rebuilding on deps revision update

.github/workflows/build_deps.yml
Properly sets deployment target for libvpx to ensure macOS 10.13 compatibility.
libvpx does not use the `MACOSX_DEPLOYMENT_TARGET` environment variable but requires a different target parameter in its configuration step.
Without this change the compiler adds `____chkstk_darwin` symbols that are not available on macOS 10.13 and make OBS crash on these systems.
Debugged the entire build process on CI and checked the resulting deps to not contain the symbol
=> CI: Fix libvpx deployment target

.github/workflows/build_deps.yml, templates/build-script-macos.tpl
Adds speexDSP to pre-built dependencies to ensure macOS 10.13 compatibility.
All dependencies used by OBS need to be built with a minimum deployment target of 10.13 - when installed via Homebrew a dependency is installed compiled against the host OS which introduces a symbol not available on 10.13.
SpeexDSP built locally and configured/built OBS with it.
=> CI: Add speex to pre-built dependencies on macOS to ensure 10.13 support

.github/workflows/build_deps.yml, Brewfile, utils/build_script_generator.py
Fixes library corruption introduced by GitHub Actions cache's use of BSD tar.
For some as of yet unknown reason BSD's tar can introduce corruptions to dylib's archived by it, as used by GitHub Actions' caching functionality. Using `gnu-tar` fixes this, but requires some workarounds to "hide" its own dependencies from our built dependencies.
`gnu-tar` will be installed by default on GitHub Actions macOS runners around January, so we would have to make these changes anyway.
For more information see also: https://github.com/Homebrew/brew/issues/6539
Build dependencies on my fork, the re-run the workflow to use caches and checked the libraries again.
=> CI: Add gnu-tar to build dependencies for CI

.github/workflows/build_deps.yml
Unifies the library paths for macOS-deps to all use `/lib/´ instead of a mishmash between `/bin/` and `/lib/`.
Also has the added benefit that when combined with macOS-qt-deps `/bin/` contains mostly Qt's utilities.
Fixes issue with ffmpeg not finding x264 at the correct path.
Built the dependencies locally as well as OBS itself with these deps.
=> CI: Unifies macOS library paths to fix ffmpeg not finding x264

.github/workflows/build_deps.yml
Fixes libjansson being packaged with outdated dylib ID.
In https://github.com/obsproject/obs-deps/commit/89367e2ed35b4ae2336dfeb4aea60da291623ea5 libjansson was fixed to be placed in `/lib/` but because the cache revision was not changed the final release packaged outdated libjansson with a wrong glib ID.
Needs to be tested on CI as it's dependent on a cache-entry miss for updated libjansson specs.
=> CI: Fix missing cache revision for libjansson

.github/workflows/build_deps.yml, README.md, build-script-macos-01.sh, build-script-macos-02.sh
This change updates the build scripts so that, when they are run on an Apple Silicon Mac, they will build the dependencies for an Apple Silicon Mac.
All of the dependencies build without any changes, except for libvpx and Qt. libvpx 1.9.0 does not support building for arm64 on macOS, but the master branch code does, so for the time being, we have to clone and then build from the master branch. Qt needs to be coerced to build for arm64 using the variable QMAKE_APPLE_DEVICE_ARCHS.
Apple is switching CPU architectures. In a few years, they won't be shipping or supporting Intel Macs anymore, so it's time to start producing a build for the new Apple Silicon Macs.
I tested my changes on my Apple Development Platform running Xcode 12.4. Both scripts complete successfully, and running `lipo …
=> CI: Build OBS dependencies for Apple Silicon Macs

.github/workflows/build_deps.yml
Use `uname -m` instead of `arch` to set `QMAKE_APPLE_DEVICE_ARCHS` when building Qt.
Currently, `QMAKE_APPLE_DEVICE_ARCHS` is set using `arch`, which returns `i386` for Intel-based machines. `QMAKE_APPLE_DEVICE_ARCHS` expects `x86_64`, which `uname -m` returns. Both `arch` and `uname -m` return `arm64` on Apple M1 machines.
With `QMAKE_APPLE_DEVICE_ARCHS` being set by `arch` (result `i386`), Qt 5.15.2 failed to build on my 2018 Mac Mini (6-core) running macOS 11.2. Setting `QMAKE_APPLE_DEVICE_ARCHS` using `uname -m` (result `x86_64`) resolved this issue. 
=> CI: Use 'uname -m' for QMAKE_APPLE_DEVICE_ARCHS

.github/workflows/build_deps.yml
Changed `CXX=="/usr/local/bin/g++"` to `CXX="/usr/local/bin/g++"`
Untested as I don't have a machine running macOS 10.13
=> CI: Remove extra '=' in env var assignment

templates/build-script-macos.tpl, templates/build-script-ubuntu.tpl
* Removed incorrect use of `$` in tpl file.
* Quote passed-in argument (path) of `ensure_dir` function. 
* `cleanup ${workspace}` expands to `cleanup $${BASE_DIR}`
* Without quoting, paths with spaces 
Created a bash script containing existing & fixed function `ensure_dir`. When passing a directory containing spaces, the existing function failed to work as intended; the fixed function correctly handled the directory with spaces.
=> CI: Fix caught_error function. Quote paths in ensure_dir

.github/workflows/build_deps.yml
Enables functionality to trigger artifact creation even for pull requests if the `SEEKING_TESTERS` label is added to a pull request on Github.
Allows testing of binaries generated by updated build scripts without the need to merge into the main codebase.
* Needs to be tested as part of this PR
=> CI: Add ability to enable artifact building with Github label

.github/workflows/main.yml, CI/include/build_support.sh
Fixes the output of ccache detection which will exit with a non-zero return code if any of the listed compilers isn't present.
Avoid build errors on systems where `clang` is not installed.
* Tested locally
=> Fix ccache status output

.github/workflows/main.yml, CI/include/build_support_macos.sh
Enables per-architecture deployment targets for CI builds.
During dogfooding it became aware that in contrast to the PR to enable M1 support for obs-studio the obs-deps repo still uses the same deployment target for arm64 and x86_64. As we use the per-architecture variant for building OBS now, this was an oversight.
* Tested with x86_64 and arm64 builds
=> Make deployment targets architecture aware

CI/build-deps-macos.sh
Remove spurious QMAKE_QUIET variable from deps build script
This flag appears to be used in the build-qt-macos.sh script and built_qt.sh script, but it is not used in the build-deps-macos.sh script or its related component scripts.
Unused variables are bad.
=> Remove spurious QMAKE_QUIET from deps build script

.github/workflows/main.yml, CI/macos/build_qt.sh, CI/macos/patches/QTBUG-97855.patch
Updates the GitHub action used to create releases with a community variant as GitHub's own has been archived and is non-maintained.
Also adds the checksums of generated downloads to release body and fixes an obscure build bug with Qt.
Keep GitHub action maintained and current, also makes it easier to update workflows using these dependencies to implement hash checks.
* Test on fork with commits to master branch and release tags
=> Update create release action

CI/windows/build_librist.sh
Librist is built without pthread through a shim. So it's not necessary to use -Wl,-Bstatic -pthread as a linking argument since pthread is not used. The argument is therefore removed.
Code cleanup.
The linking argument is not used since pthread is not included so it is innocuous.
But this is cleaner that way.
Built librist.dll , checked it had no stray dll (libgcc nor libwinpthread).
Then checked that obs-studio streamed fine to a rist server by watching a stream on a web player.
=> windows: Remove an LDARG which is not used.

.github/workflows/windows_deps.yml
windows: Build AJA debug library
The OBS AJA plugin (aja) currently requires both the Release and Debug versions of the ajantv2 library to be able to build. This enables CI to build both Release and Debug versions of the library. Local builds with the build-deps-windows-native.ps1 script will still only produce a single build in the RelWithDebInfo configuration. 
Make using obs-deps easier.
=> windows: Build AJA debug library

.github/workflows/windows_deps.yml, CI/package-deps-windows.ps1, CI/windows/build_libvpx.sh, CI/windows/build_libx264.sh, CI/windows/build_luajit.ps1, CI/windows/build_mbedtls.sh, CI/windows/build_zlib.sh
This PR introduces two changes to windows-reps:
1. It ensures all import libraries and static libraries (`.lib` suffix) are placed inside the `lib` folder.2. 
2. On top of the classic "combined" dependency download, it also creates separate x64 and x86 downloads
CMake finders expect libraries to be found inside the `lib` directory of a specified PREFIX path. While OBS' own finders use multiple directories as additional "hints" for finding dependencies, the defaults ones do not and are stricter in this regard.
This mainly affects "cURL" within a standard OBS build and required adding additional paths to the `CMAKE_PREFIX_PATH` in the CMake rework. By placing the static libraries and import libraries in the correct directory, no additional paths are needed for PREFIXES or custom CMake …
=> CI: Fix static library placement and create architecture-dependent release artifacts (Windows)

.github/workflows/main.yml, CI/macos/build_qt.sh
Port some configuration options from our Windows Qt build to our macOS Qt build to reduce the build time and build size.
Reducing the build time helps us validate PRs and commits faster and lets us free up macOS CI instances faster.
I let this build on my fork's CI. I checked the build time and artifact size. Both build time and artifact size were reduced from before these changes.
If we want to be thorough, someone should build OBS on macOS against this Qt build to make sure that nothing breaks.
* x86_64: 1h09m35s
* arm64: 1h36m29s
* x86_64: 18.9 MB
* arm64: 20.5 MB
* universal: 28.3 MB
* x86_64: 83.2 MB
* arm64: 99.9 MB
* universal: 140 MB
* x86_64: 43m15s
* arm64: 1h13m13s
* x86_64: 12.8 MB
* arm64: 15.3 MB
* universal: 19.2 MB
* x86_64: 62.0 MB
* arm64: 78.1 MB
* universal: 100 MB …
=> CI: Optimize macOS Qt build

.github/workflows/main.yml
Use the hash of the Qt patches for the cache key for the Qt build jobs. Use restore-keys to do a fuzzy-match to restore the cache if the exact cache key is not found. This should allow us to restore the Qt cache and do a rebuild if the patches used for Qt change. This means we don't have to remember to change the QT_REVISION variable if we add new patches or change the existing ones.
Hopefully, we can avoid full rebuilds of Qt on CI when we've just changed patch files. We're still unsure how well this will work, so it might be best to merge this and see how the subsequent Qt patch PRs (#101 and #102) behave.
Edit:
This will only force a rebuild if the Qt patches have changed. It won't let us do partial rebuilds by itself. For that, we would need to also cache the intermediate build …
=> CI: Improve Qt caching

CI/macos/build_qt.sh, CI/macos/patches/QTBUG-88495.patch, README.md
Adds https://github.com/qt/qtbase/commit/6d306a0 to our patches.
The problem itself doesn't seem to be easily reproducible (Matt couldn't do so), but it always happens to me and doesn't anymore with QT built with this patch (you can find test artifacts from GHA [here](https://github.com/gxalpha/obs-deps/actions/runs/2141442917)).
Before:
After:
Fix https://github.com/obsproject/obs-studio/issues/4041 until we move to QT6.
Built QT on GitHub Actions (see link above) and compiled OBS against the build artifact.
=> macos/patches: Cherry-Pick QT macOS text spacing patch

CI/macos/build_qt.sh, CI/macos/patches/QTBUG-70137-1.patch, CI/macos/patches/QTBUG-70137-2.patch, CI/macos/patches/QTBUG-70137-3.patch, README.md
Backports qt/qtbase@78b6050 and qt/qtbase@3224c6d, fixing the broken macOS
docking and undocking.
These fixes are documented to fix [QTBUG-70137](https://bugreports.qt.io/browse/QTBUG-70137), where docks will freak out when getting dragged out of the UI; however they also happens to fix [QTBUG-64483](https://bugreports.qt.io/browse/QTBUG-64483) (floating docks randomly deciding they lost their will to live, and no longer being re-dockable) (@RytoEX has been watching that one).
These two bugs were the biggest troublemakers in terms of docking and undocking on macOS.
The patches are no longer needed once we move to QT 6.2 (which is where they are from), but for now I think they are really important (and perhaps could even justify a macOS hotfix on their own).
Docking can get very broken on …
=> macos/patches: Backport QT macOS docking fixes

deps.macos/50-libpng.zsh
Fixes libpng being shipped as a dynamic library with obs-deps on macOS.
libpng is just needed for FFmpeg and freetype as a static library. As the non-FFmpeg-deps are built as shared libraries, libpng got built as a shared library as well and thus shipped with the package.
This commit forces libpng to be built as a static library, so freetype can pick it up, but it will be removed before packaging.
Tested in local obs-deps build runs on macOS.
=> libpng: Fix shared library being shipped with macOS dependencies

.github/workflows/main.yml, build-deps.zsh
Fix obs-studio build scripts failing due to misnamed qt release artefacts.
Current obs-studio build scripts expect Qt artifacts to be named `macos-deps-qt-...` - to avoid a breaking change, this commit restores this naming convention.
Built qt artefact locally on macOS machine.
Note that this will require a release run on another fork to check release creation, will undraft PR if this has been confirmed.
=> CI: Fix name of the generated Qt artifact added to release

.gitattributes, .github/actions/build-windows-qt/action.yml, .github/actions/package-windows-qt/action.yml, .github/workflows/main.yml, Build-Dependencies.ps1, deps.qt/checksums/jom-1.1.3.zip.sha256, deps.qt/patches/Qt5/win/0001-QTBUG-74606.patch, deps.qt/qt5.ps1, deps.qt/qt6.ps1
Add Qt 5 and Qt 6 builds for Windows 32-bit and 64-bit with both RelWithDebInfo and Debug configurations. This also adds Release PDBs to the Qt builds and offers them as a separate release asset on releases.
We want to provide an easy way to build Qt locally and on CI in the same configuration that we use regularly.
I have run and re-run these build scripts locally and on my fork's CI. I have also tested the release job on my fork. I have built OBS Studio against artifacts from these runs locally by updating the Qt version for the Windows build scripts.
The one caveat I've found is that we get some new LNK4099 warnings in MSVC (expected a PDB file for a library, but PDB not found) due to building Qt in Release but with PDBs, instead of building in `-debug-and-release` mode, where …
=> Add Qt Windows builds

Build-Dependencies.ps1, deps.windows/50-bison-bin.ps1, deps.windows/50-bison-dep.ps1, deps.windows/50-pcre.ps1, deps.windows/50-swig.ps1, deps.windows/checksums/bison-2.4.1-bin.zip.sha256, deps.windows/checksums/bison-2.4.1-dep.zip.sha256, deps.windows/checksums/pcre2-10.40.zip.sha256, deps.windows/patches/swig/0001-add-Python-3-stable-abi.patch, deps.windows/patches/swig/0002-remove-PCRE-cmake-finder.patch, utils.pwsh/Invoke-GitCheckout.ps1
Adds swig to precompiled binaries for Windows with applied patch for Py3 stable ABI patch.
Support for the Python 3 stable ABI allows Python scripting support in OBS to use a wider range of available Python 3 versions vs. being pinned to the version the scripting module is compiled with.
* Built and packaged Swig locally
* Compiled obspython with Swig compiled with these changes
=> windows-deps: Add patched swig binary with support for Py3 stable ABI

utils.pwsh/Invoke-DevShell.ps1, utils.pwsh/Setup-Target.ps1
After failing to build obs-deps on Windows, coordinated with @PatTheMav to find a solution that'd fix building.
If multple copies of VIsual Studio are detected, sort the list and choose the oldest version installed.
If more than one copy of Visual Studio is installed, `MSFT_VSInstance` will return an array of objects, causing the rest of the build script to fail.
Additionally, detours failed to build as it bypassed the Find-VisualStudio function, resulting it bypassing the included fix.
* Attempt to build obs-deps on a machine where more than one version/copy of Visual Studio is installed.
* Tested with 2019 and 2022 installed. With these changes, 2019 is selected.
=> Properly support multiple VS versions on Windows

utils.pwsh/Setup-Dependency.ps1
Fix obs-deps releases created from cache missing patched Swig library files.
When build directories are restored from cache on CI, it is expected that patched files stay patched. Without this fix, a git checkout takes place, which resets files to their unpatched state.
* Needs to be tested on CI (uncached + cached runs).
=> utils.pwsh: Skip git checkout if SkipUnpack is passed

deps.ffmpeg/99-ffmpeg.zsh
For Windows targets, the arch strings are x86 and x64 rather than x86 and x86_64.
We want AV1 encoders to work.
Checked locally that AV1 encoders are now enabled.
=> deps.ffmpeg: Fix AV1 encoder enablement

.github/workflows/main.yml, utils.pwsh/Setup-Target.ps1
This PR contains two commits. They can be split into separate PRs if needed.
----
utils.pwsh: Implement preferred Visual Studio versions
Allow preferring specific versions of Visual Studio by checking the ChannelId property. This allows trivial switching of what version of Visual Studio to use, though we still have a hard floor of VS2019.
----
Use VS2022 by default
This commit makes the necessary changes to the GitHub Actions workflow and to utils.pwsh/Setup-Target.ps1 to use VS2022 by default, and then fallback to VS2019 if VS2022 is not available.
----
Want to switch to VS2022.
Tested locally.
=> Use Visual Studio 2022

.github/actions/build-windows-qt/action.yml, deps.qt/patches/Qt6/win/0001-QTBUG-86344.patch, deps.qt/qt6.ps1
Backport a fix from qt/qtbase@e3201e7124 to help address setups with multiple displays with different scale factors.
This patch can be dropped once we reach Qt 6.4.0 or newer.
Requested by @jpark37.
Tested builds of Qt locally.
=> deps.qt: Backport Windows native scale factor fix

deps.windows/40-vulkan.ps1, deps.windows/checksums/VulkanSDK-1.2.131.2-Installer-Components.7z.sha256
This reverts commit e03731a967298ce9915555a50377ff3b877b54db.
Updating Vulkan is more trouble than it's worth right now. Let's revert for now and update this some other time.
Want to ship new deps. Don't want to mess around with trying to make sure game capture works with updated Vulkan files.
We've previously used this.
=> Revert "deps.windows: Update VulkanSDK to 1.3.216.0"

deps.ffmpeg/60-srt.zsh
Symbols for pthread and mbedtls were being exported in libsrt.dll, which was causing symbol conflicts and crashes.
Want SRT to work. Don't want crashes.
Tested locally, but want to see what CI produces.
=> deps.ffmpeg: Exclude symbols from SRT DLLs

deps.qt/qt6.zsh
The macOS Qt6 Universal build fails on GitHub actions due to a suspected bug in vcpkg. Disable using vcpkg until a proper fix is found.
This is an RFC pull request. I don't know if it is the best solution and I'm looking for feedback.
Fixes: #135
Has had some minimal testing on an unattached repo (https://github.com/glikely/obs-deps-2. Will get a full test when the CI Action is approved for this pull request.
=> deps.qt: Fix macOS build by disabling VCPKG

.github/actions/build-ffmpeg/action.yml, .github/actions/build-macos-deps/action.yml, .github/actions/build-macos-qt/action.yml, .github/actions/build-windows-deps/action.yml, .github/actions/build-windows-qt/action.yml, .github/actions/create-single-arch/action.yml, .github/actions/create-universal/action.yml, .github/actions/package-windows-qt/action.yml, .github/workflows/main.yml
GitHub Actions has deprecated set-output. Replace usages of set-output in stdout with the new syntax to save the output to the new environment variable.
See:
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Don't want deprecation warnings hiding real issues.
It hasn't. This was written by following documentation. A CI run will be the test.
=> Update GitHub Actions for set-output deprecation

utils.pwsh/Invoke-DevShell.ps1, utils.pwsh/Utils-Patch.ps1
Fixes issues in `Invoke-DevShell` and `Utils-Patch` due to PowerShell 7.3.0 becoming available on Windows runners.
Fix Windows build jobs on GitHub Actions.
Tested updated scripts on local Windows 11 VM.
=> utils.pwsh: Fix issues with Powershell 7.3.0

deps.ffmpeg/60-mbedtls.zsh, deps.ffmpeg/60-srt.zsh, deps.macos/30-jansson.zsh
Fixes broken Xcode bundle composition by removing symlink chains from unversioned dynamic library names.
CMake by default generates dynamic libraries with a full semver filename and two symlinks:
* A major version symlink pointing to the semver file
* An unversioned symlink pointing to the major version symlink
Xcode's file copy step used to move Frameworks into an app bundle only resolves a single level of symlinks, so with this setup a symlink is copied into the bundle, which then fails at the codesigning step.
Behaviour has been reported to CMake (https://gitlab.kitware.com/cmake/cmake/-/issues/24174#note_1277980) as well as Apple. These fixups should mitigate this in the short term.
Built all fixed libraries locally and checked generated symlinks.
- Bug fix (non-breaking change which …
=> macOS: Fix shared library symlinks breaking Xcode bundle composition

deps.windows/30-jansson.ps1
Add Jansson 2.14 to the Windows deps. Mimic our existing in-tree build options as much as possible, except don't override JANSSON_STATIC_CRT. The default value is OFF, which in turn means /MT and /MTd are NOT set, which is seemingly what we want. Our in-tree build overrides JANSSON_STATIC_CRT to ON, but then also forces /MT and /MTd to NOT be set. JANSSON_STATIC_CRT only controls whether or not those flags are set, so just leave it OFF.
Jansson adds 20-30 seconds to the CMake configuration time of my local builds, and adds 40-60 seconds on CI builds. If we prebuild it, we can avoid that needless expenditure of time. Want to pull in-tree deps out of the obs-studio tree where feasible.
Tested locally and I can build Release obs-studio just fine. However, trying to build in Debug results in …
=> deps.windows: Add Jansson to Windows deps

deps.qt/qt6.ps1, utils.pwsh/Setup-Target.ps1
The Strawberry Perl installation is poisoning all of our native Windows builds (notably, FreeType, curl, PCRE, and Qt6). For now, ignoring its default installation path is likely the easiest solution.
Also, force Qt6 Windows builds to use bundled 3rd party libraries when possible (e.g., ZLIB, libpng, libjpeg).
Want CI builds to stop failing.
While I have PRs ready for tightening up the FreeType and curl builds (FreeType manages to succeed regardless, the curl PR seemed to work), PCRE was the next to fail. We may want to continue fixing them individually one by one, and then apply this for future cases, or perhaps we don't want this, and we'd rather fix them all individually. In any case, I'm opening this PR to provide us the option of which path to choose.
CI is the test.
- Bug fix …
=> utils.pwsh: Ignore Strawberry Perl default path

deps.windows/30-speexdsp.ps1, deps.windows/patches/speexdsp/0001-Add-CMakeLists.patch
This caused a build failure recently, and we determined that it's safer to build without these options.
We apparently have been lucky enough to never run into this failure since this was added back in #79.
Don't want build failures.
Has not been tested yet. CI should at least tell us if SpeexDSP will build. Will try to test before merging unless others think this is fine.
=> deps.windows: Remove GL/LTCG from SpeexDSP CMake patch

deps.windows/30-curl.ps1
Previously, curl would attempt to find ZLIB, and could continue even if ZLIB was not fully found. This could result in a scenario where ZLIB includes were found, but ZLIB libraries were not found, and the curl build would continue and succeed anyway. Examining previous builds, it seems that this was the case for our dependencies.
A recent build failure on CI (windows-2022, version 20221120.1) had CMake find the x64 ZLIB libraries from CI's Strawberry Perl install location, which caused a build failure for the x86 dependencies due to mismatched architectures. The version of Perl did not change between the image versions, so I suspect some other change, possibly in CMake (or curl), that caused it to suddenly find the libraries.
Since ZLIB was not actually being used, let's simply disable it …
=> deps.windows: Explicitly disable ZLIB with curl

deps.macos/50-libpng.zsh
Remove unnecessary fixup function for Windows target on macOS deps script.
The fixup function is a bad copy paste error that does nothing on deps for macOS.
Let's see if the CI likes this. Shouldn't be too bad.
- Bug fix (non-breaking change which fixes an issue) 
=> deps.macos: Remove unnecessary fixup for Windows target

deps.qt/checksums/qtbase-everywhere-src-6.3.1.tar.xz.sha256, deps.qt/checksums/qtbase-everywhere-src-6.4.1.tar.xz.sha256, deps.qt/checksums/qtimageformats-everywhere-src-6.3.1.tar.xz.sha256, deps.qt/checksums/qtimageformats-everywhere-src-6.4.1.tar.xz.sha256, deps.qt/checksums/qtmultimedia-everywhere-src-6.3.1.tar.xz.sha256, deps.qt/checksums/qtmultimedia-everywhere-src-6.4.1.tar.xz.sha256, deps.qt/checksums/qtshadertools-everywhere-src-6.3.1.tar.xz.sha256, deps.qt/checksums/qtshadertools-everywhere-src-6.4.1.tar.xz.sha256, deps.qt/checksums/qtsvg-everywhere-src-6.3.1.tar.xz.sha256, deps.qt/checksums/qtsvg-everywhere-src-6.4.1.tar.xz.sha256, deps.qt/patches/Qt6/win/0001-QTBUG-86344.patch, deps.qt/qt6.ps1, deps.qt/qt6.zsh
This reverts commit 0b22ceded4e033711e07cdd5169f7d686e2a5892.
This rolls back Qt on Windows from 6.4.1 to 6.3.1 due to a [previously mentioned debug assert](https://github.com/obsproject/obs-deps/pull/141#issuecomment-1316439656) that has not been resolved. As far as I know, the debug assert only occurs on Windows in VS2022, but it was also recommended to roll back Qt on macOS.
We decided that if this wasn't resolved in time for OBS 29, that we'd roll it back.
OBS 28.1 ran on Qt 6.3.1.
=> Revert "deps.qt: Update Qt6 to Qt 6.4.1 for Windows"

build-deps.zsh, deps.ffmpeg/20-opus.zsh, deps.ffmpeg/30-libogg.zsh, deps.ffmpeg/30-libvorbis.zsh, deps.ffmpeg/60-mbedtls.zsh, deps.ffmpeg/60-srt.zsh, deps.ffmpeg/70-librist.zsh, deps.ffmpeg/99-ffmpeg.zsh, deps.macos/10-speexdsp.zsh, deps.macos/30-jansson.zsh, deps.macos/40-luajit.zsh, deps.macos/50-libpng.zsh, deps.macos/60-freetype.zsh, deps.qt/qt6.zsh, utils.zsh/20-host.zsh, utils.zsh/functions/fix_rpaths
Fixes generated macOS libraries to not use versioned SONAMEs if possible and fix MACHO header `id` values to match those unversioned variants.
Using versioned library names is common on Linux to discern between the _actual_ version of a library (`some_lib.so.4.5.1`), the compatibility version (usually the major version `some_lib.so.4`) that should be API-compatible, and a fallback name (`some_lib.so`), with the latter two pointing to the actual library via symlinking.
macOS uses two values in its `LC_ID_DYLIB` header (`current` and `compatibility`) which are used by its library loader to check if a library is compatible - the actual file names are not used.
A binary should link to a library (`some_lib.dylib`) via the `LC_LOAD_DYLIB` header, which itself also contains `current` and …
=> Update obs-deps for CMake 3.0 macOS update

build-deps.zsh, deps.macos/90-sparkle.zsh, deps.macos/90-vlc.zsh, deps.macos/checksums/Sparkle-2.3.2.tar.xz.sha256, deps.macos/checksums/vlc-3.0.8.tar.xz.sha256
Adds libVLC headers and Sparkle framework (+dSYM) to obs-deps.
Reduces complexity for build system setup on macOS as obs-deps will contain almost every build-time dependency on macOS. Also limits possible availability issues of videolan's servers to the time of an obs-deps release instead of every time obs-studio is built.
Build obs-deps with both dependencies, checked Framework files and headers are put to the correct destinations.
=> deps.macos: Add VLC and Sparkle dependencies

deps.windows/20-freetype.ps1
FT_WITH options were replaced with FT_DISABLE and FT_REQUIRE pairs in FreeType 2.11.1. Let's update to the correct options.
References:
https://github.com/freetype/freetype/commit/1f742f05bf21234236b54f52c3ef8cc8973131b1
Want to use the correct CMake options. We can probably reevaluate why we are using these later though.
Tested this locally back in November. Should still be fine.
=> deps.windows: Update FreeType CMake flags

deps.windows/90-vlc.ps1, deps.windows/checksums/vlc.zip.sha256, utils.pwsh/Invoke-SafeWebRequest.ps1
Adds libVLC headers to obs-deps.
Reduces complexity for build system setup on Windows as obs-deps will contain almost every build-time dependency. Also limits possible availability issues of videolan's servers to the time of an obs-deps release instead of every time obs-studio is built.
Build obs-deps with both dependencies, checked headers are put to the correct destinations.
=> deps.windows: Add VLC to Windows dependencies

.github/actions/package-windows-qt/action.yml
The Windows Qt packaging step takes about 10 minutes on CI. We only need the maximum compression level on releases, so let's try using the default compression level on other events to see if that speeds up those CI runs.
Want slightly faster Windows CI runs.
CI is the test. I want to compare the run time and artifact size.
=> CI: Reduce Qt package compression level when not tagging

deps.qt/patches/Qt6/mac/0001-QTBUG-106369.patch, deps.qt/qt6.zsh
Backports qt/qtbase@441993a9 which will only be in Qt 6.5.1 and later.
*In theory* we could also add it to our Qt 5.15 builds but realistically we're never going to use those again.
Currently, OBS is basically unusable with the accessibility keyboard enabled, as every time you type something in a dialog OBS will crash when closing the dialog.
This is very much sub-optimal.
The commit in Qt unfortunately made it neither into 6.4.3 (which will be the last 6.4 release) nor 6.5.0, both of which (at least the RC) are due to be released in the coming days, and is only in 6.5.1.
I think this is a fix worth including however.
Tested that with current obs-deps it still crashes.
Tested both with the Qt dev branch as well as a [CI build of this …
=> deps.qt: Backport macOS accessibility keyboard crash fix

deps.ffmpeg/40-aom.zsh
AOM allows you to set the target CPU arch (AOM_TARGET_CPU) at configure time. If not specified, their CMake will attempt to autodetect this value based on CMAKE_SYSTEM_PROCESSOR. The value of AOM_TARGET_CPU is then used to enable various optimizations.
We used to not set a value for AOM_TARGET_CPU.[1] We started setting a value for it with the unified FFmpeg build. However, we set the value of "arch" based on the build target string (i.e., windows-x86 or windows-x64), which results in an "arch" of "x86" or "x64". AOM's CMake does expect the value "x64" as a possible value of AOM_TARGET_CPU, as it instead expects "x86_64".[2] However, it will not produce a configure error if given "x64" for the value of AOM_TARGET_CPU. It will accept this value, but then subsequent checks will rely on the …
=> deps.ffmpeg: Fix AOM target CPU arch

utils.zsh/30-build.zsh
Fix a typo so that we actually specify the C++11 standard.
Want this to use the correct flag and intended value.
I haven't built locally. I'm hoping CI will be green.
=> utils.zsh: Use C++11 standard by default

deps.ffmpeg/99-ffmpeg.zsh
FFmpeg n6.0 has a bug with NVENC that causes OBS to crash. It was fixed in the commit immediatley after the n6.0 tag. There is currently no n6.0.1 tag, so update to the latest release/6.0 commit so that OBS does not crash when using FFmpeg NVENC.
Don't want OBS crashes.
I haven't tested this. I am mostly hoping that `release/6.0` is stable enough to pull the latest commit until n6.0.1 comes out.
=> deps.ffmpeg: Update FFmpeg to 3980415627

deps.ffmpeg/99-ffmpeg.zsh, deps.ffmpeg/patches/FFmpeg/0001-flvdec-handle-unknown.patch, deps.ffmpeg/patches/FFmpeg/0002-libaomenc-presets.patch
Adds a fix for NVENC DTS being wrong when b-frames are enabled. Also cleans up FFmpeg patches by splitting them up into separate files.
See https://github.com/obsproject/obs-studio/pull/8582
Less pain.
@tt2468 confirmed it fixed DTS with NVENC on his machine.
=> deps.ffmpeg: Update FFmpeg and separate out patches

build-deps.zsh
Adds required `VERSION` file for Qt packages.
When building libobs for plugins, prebuilt dependencies are already downloaded for the main plugin build. Current obs-studio doesn't correctly detect existing Qt dependencies as they're missing the required `VERSION` file.
Tested with manually added `VERSION` file in a plugin build.
=> deps.qt: Add missing obs-deps version file for Qt packages

.github/actions/create-universal/action.yml
Adds detection of single-architecture static library to GitHub action responsible for generating universal architecture builds.
Fixes compile issues for plugins which should default to universal binaries.
Tested on macOS 13.
=> CI: Add detection for single-arch static libraries

deps.macos/90-syphon.zsh, licenses/syphon/License.txt
Adds syphon to obs-deps.
The workflow pulls their git repository (https://github.com/Syphon/Syphon-Framework) at the specified git commit (they don't seem to tag releases anymore).
Building builds the `Syphon` target of their distributed Xcode project, which generates a `Syphon.framework`.
Along with the debug symbols, this then gets copied to the `lib` directory.
The OBS syphon plugin is currently using a 9(!) year old version of the syphon framework on a OBS contributors' fork because it had to be patched for IOSurfaces to be accessible (fun fact: Not counting the custom patches, it's exactly 9 years old to the day, see the [commit history](https://github.com/palana/Syphon-Framework/commits/master)).
Seeing that obs-deps wasn't a thing back then, it currently is a git submodule. This …
=> deps.macos: Add Syphon Framework

utils.pwsh/Setup-Target.ps1
This prevents an error where the Visual Studio generator extraction thing would work incorrectly if you had only the Build Tools installed.
If you have the Visual Studio Build Tools installed, and not a full copy of Visual Studio, building cmake things would fail, as the output of `Find-VisualStudio` would be something along the lines of this:
```
Caption           : Visual Studio Build Tools 2022
Description       : The Visual Studio Build Tools allows you to build native and managed MSBuild-based applications
without requiring the Visual Studio IDE. There are options to install the Visual C++ compilers and
libraries, MFC, ATL, and C++/CLI support.
ElementName       : Visual Studio Build Tools 2022
InstanceID        : Microsoft:VisualStudio:e66d2ae7
IdentifyingNumber : e66d2ae7
Name …
```
=> utils.pwsh: Fix CMake error with VS Build Tools

.github/actions/build-windows-deps/action.yml, .github/workflows/main.yaml, .github/workflows/scheduled.yaml, Build-Dependencies.ps1, build-deps.zsh, deps.windows/20-freetype.ps1, deps.windows/30-cmocka.ps1, deps.windows/30-curl.ps1, deps.windows/30-jansson.ps1, deps.windows/30-rnnoise.ps1, deps.windows/40-luajit.ps1, deps.windows/50-pcre.ps1, deps.windows/50-swig.ps1, deps.windows/60-nlohmann-json.ps1, deps.windows/60-ntv2.ps1, deps.windows/60-python.ps1, deps.windows/60-websocketpp.ps1, deps.windows/60-zstd.ps1, utils.pwsh/Invoke-DevShell.ps1, utils.pwsh/Setup-Target.ps1
* Disables x86 builds for all dependencies not required by x86-only modules.
* Moves luajit and Swig files into their canonical locations expected by default CMake find rules.
* Uses VSSetup PowerShell module to find Visual Studio installations in a more portable manner (also supports ARM64 Windows hosts)
* Creates obs-deps `VERSION` file in Windows packages
* Enables compatibility with CMake 3.0 upgrade for Windows
* Removes complexity for CMake finders in said upgrade (canonical paths are used)
* Enables use of a single x64 project for Windows
Tested builds on Windows 11
=> deps.windows: Update dependencies for CMake 3.0 upgrade

deps.macos/80-qrcodegencpp.zsh, deps.windows/60-qrcodegencpp.ps1, licenses/qrcodegencpp/QR-Code-generator/Readme.markdown, licenses/qrcodegencpp/qrcodegen-cmake/LICENSE
Some Linux distribution (e.g. Ubuntu, Fedora) tweak https://github.com/nayuki/QR-Code-generator to ship it's C and C++ implementations as libraries.
One of the methods is to add files from https://github.com/EasyCoding/qrcodegen-cmake and use CMake to build the libraries which is the method took for this PR.
The C implementation (libqrcodegen) is removed since it is not needed.
I'm aware of #174, so if it get merged first, I will update the pwsh script to add `$Targets`.
Reduce the number of submodules in obs-studio repo and provides those as libraries in obs-deps.
Also this would allow to make obs-websocket submodule-less.
CI test build static version, and tested shared on VMs.
https://github.com/tytan652/obs-studio/pull/13 provides binaries:
- Ubuntu 20.04 is failed too because of an …
=> Add Libqrcodegencpp

.github/workflows/main.yaml
Updates FFmpeg build jobs to use macOS 13-based runners.
macOS 13-based runners have more recent hardware than macOS 12-based runners and allow us to cut down on compilation time and also target more recent macOS versions moving forward.
As this changes CI workflows, test will be conducted by running the pull request workflow.
=> CI: Update FFmpeg build jobs to use macOS 13-based runners

.github/workflows/main.yaml
Adds condition to check for unsuccessful cache restoration to cache saving step in macOS dependency build job.
Compilation cache needs to be saved only if no successful restoration took place.
Needs to be tested on CI.
=> CI: Fix unnecessary cache save attempt for Ccache contents

deps.windows/70-vpl.ps1, licenses/vpl/LICENSE.txt
Adds vpl v2023.3.0 (latest) headers for obs-qsv11.
Linked with PR: https://github.com/obsproject/obs-studio/pull/9142
Updates Intel MSDK to Intel VPL API to support future Intel hardware. Removes the MSDK files from the obs-studio repo with deprecated MSDK functions and links the VPL headers to obs-qsv11.
Testing is described in the linked obs-studio PR 
- [x ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x ] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x ] My code is not on the master branch.
- [x ] The code has been tested.
- [x ] All commit messages are properly formatted and commits …
=> deps.windows: Add VPL

deps.ffmpeg/60-mbedtls.zsh, deps.windows/10-mbedtls.ps1
This updates to mbedTLS 3.4.0.
Keep libraires up to date.
Tested only with the libdatachannel PR on windows + WHIP PR; it works fine on hours of testing.
=> deps.ffmpeg: Update mbedTLS to 3.4.0

deps.macos/80-carla.zsh, deps.windows/60-carla.ps1
Here comes the obs-deps side for carla plugin host stuff. :)
Adds carla as a build dependency for macOS and Windows.
Windows builds use MSVC, and both through cmake.
This is a requirement for https://github.com/obsproject/obs-studio/pull/8919
Instead of pulling in all of carla as a git submodule inside OBS, we build carla separately here (and only the necessary stuff, the PyQt Carla frontend is not neeeded for example)
I have tested that this works by making a release on my obs-deps fork https://github.com/falkTX/obs-deps/releases/tag/2023-06-01
Verified that the release artifacts contain the needed files.
Then tweaked my obs-studio private fork to make sure the builds were able to be used https://github.com/falkTX/obs-studio/actions/runs/5142961834/jobs/9257394909
Everything seems good …
=> Add Carla as dependency to macOS and Windows builds

.github/workflows/main.yaml, deps.windows/70-vpl.ps1
deps.windows: Install VPL Debug library if present
Also clean up some stray whitespace.
CI: Add VPL Debug build
Similar to AJA's NTV2 library, it seems that VPL requires a separate Debug library to be able to build OBS Studio in Debug with VPL. Use the same technique that we used for NTV2 for VPL.
Want to be able to build OBS Studio in Debug with QSV+VPL enabled.
Tested locally on Windows 11 by building the VPL dependency in Debug and then building OBS Studio in Debug with a VPL enabled branch.
=> deps.windows: Add VPL debug library

Build-Dependencies.ps1, utils.pwsh/Invoke-DevShell.ps1, utils.pwsh/Invoke-SafeWebRequest.ps1
Remove code branches that handled versions of PowerShell older than PowerShell 7.0 (such as PowerShell 5.x and 6.x, or Desktop vs. Core). Increase the minimum required PowerShell version from 7.0 to 7.2 since 7.0 is no longer supported.
PowerShell 7.2 is the currently supported LTS version of PowerShell and is available on all GitHub Actions runner images. Let's shed a tiny bit of code that we don't need anymore.
Tested locally on Windows 11.
=> Clean up old PowerShell code

deps.ffmpeg/60-mbedtls.zsh, deps.ffmpeg/70-libdatachannel.zsh
Adds missing fixup step for `libdatachannel`.
Every dynamic library shipped with OBS Studio needs to properly stripped, its debug information converted into a dSYM file and also its versioned filename removed from the library ID.
Also fixes a build issue with its dependency mbedtls when using Release configuration.
Tested with local builds of `libdatachannel`.
=> deps.ffmpeg: Add missing fixup step for libdatachannel

.github/workflows/main.yaml, deps.windows/60-qrcodegencpp.ps1
Enables Debug builds of qrcodegencpp dependency
Enables Debug builds without errors on obs-studio
Built the dependency with the following command and manually copied the generated files to obs-studio/.deps/.../ folder.
```
$Params = @{
>>     Target = 'x64'
>>     Configuration = 'Debug'
>>     Dependencies = 'qrcodegencpp'
>>   }
.\Build-Dependencies.ps1 @Params
```
Checked the WebSocket was enabled once again on Debug builds.
=> CI: Enable qrcodegencpp Debug build

deps.windows/20-freetype.ps1
This was previously left unupdated because FreeType's GitHub mirror was not being updated. The mirror has since been fixed, so let's realign this with the version used on macOS.
Want to keep deps aligned across macOS and Windows as best as we can. This was intended to be updated in #202 but was not for the reasons noted here and there.
I have not tested this, but macOS has been running with this version of FreeType during the OBS 30 beta, and this is a patch update.
=> deps.windows: Update FreeType to 2.13.1

deps.ffmpeg/70-libdatachannel.zsh
Fix malformed `SONAME` and library name in CMake package file generated for `libdatachannel`.
Fixes current issue with `obs-webrtc` failing to load in OBS Studio on macOS because the dependency library cannot be resolved by the dynamic library loader.
Libraries should not be symlinked or versioned on macOS, so we need to fix not only the generated binaries but also the CMake package files to reflect this.
Built `libdatachannel` locally with the fixes applied and replaced corresponding contents in downloaded `obs-deps`, then built and ran OBS Studio to check if `obs-webrtc` is correctly loaded.
=> deps.ffmpeg: Fix libdatachannel packaging for macOS

deps.qt/patches/Qt6/win/0001-CVE-2023-43114-6.5.patch, deps.qt/patches/Qt6/win/0002-QTBUG-117779.patch, deps.qt/patches/Qt6/win/0003-QTBUG-118117.patch, deps.qt/qt6.ps1
This PR contains four commits:
1. deps.qt: Restore Patch function for Windows Qt script
The Patch function was left out of a previous rewrite.
2. deps.qt: Backport patch for CVE-2023-43114
The CVE only affects Windows.
Fixed in 6.5.4 and 6.6.0.
https://www.qt.io/blog/security-update-regarding-cve-2023-43114
https://codereview.qt-project.org/c/qt/qtbase/+/504321
http://bugreports.qt.io/browse/QTBUG-116773
3. deps.qt: Backport patch for QTBUG-117779
Fix a bug on Windows where child windows would move with the parent
window and also resize to their minimum size.
Fixed in 6.5.4, 6.6.1, and 6.7.
https://bugreports.qt.io/browse/QTBUG-117779
https://bugreports.qt.io/browse/QTBUG-118118
https://bugreports.qt.io/browse/QTBUG-118217
4. deps.qt: Backport patch for QTBUG-118117
Fix a bug on Windows …
=> deps.qt: Add Qt patches

.github/actions/build-deps/action.yml, .github/workflows/scheduled.yaml
Adds the CMake version used on a runner to the generated hash used for build caches and adds VPL and QR-Code-Generator to scheduled builds.
CMake's installation scripts will automatically remove old CMake package installations if the `<project>-targets.cmake` file to be installed differs from the one found at the installation destination.
This process will also remove any configuration-related target files found in that directory. This currently leads to the restored build directory from the GitHub Action cache to remove the files installed by the step to create the Debug configuration variant.
Forcing the cache restoration to miss if the CMake version used for the cache differs from the one currently installed on runners ensures that both steps will use the same underlying CMake version. …
=> CI: Fix issues introduced by CMake version changes when using build caches

deps.qt/qt6.zsh, utils.zsh/functions/fix_rpaths
Fixes the output file names and library IDs of Qt debug builds on macOS by forcing the use of unversioned `SONAME`s.
The Xcode bundle generation requires libraries generated by CMake to not use versioned SONAMEs (as Linux does), which Qt does by default.
Disabling this behaviour generates unversioned dynamic libraries and makes them compatible with `obs-studio`'s build system.
With this change, a local Qt debug build can be copied over downloaded `obs-deps` and will be picked up whenever the project itself is built in Debug configuration.
Tested with Debug builds on macOS 13.5.2 and current Xcode.
=> deps.qt: Fix library naming for macOS debug builds

deps.ffmpeg/40-aom.zsh, utils.zsh/functions/universal_build, utils.zsh/functions/universal_config
Fixes universal builds of `aom` on macOS by extending the functionality available for non-CMake-based projects to also override CMake variables with architecture-specific identifiers.
`aom` requires architecture-specific toolchain files to be built, but universal builds usually only require passing both modern Apple architectures to CMake to have the compiler create universal binaries by default.
Because of architecture-specific optimisations this is not possible for `aom`, so for local builds the architectures need to be built separately and then combined for the final installation.
Tested locally by building `aom` as static and shared libraries and checking the available architectures in the installed library files.
=> deps.ffmpeg: Fix local universal architecture builds of aom for macOS

.github/actions/build-qt/action.yaml, Build-Dependencies.ps1
Updates the Windows build script to explicitly identify dependency "package names" (instead of inferring them implicitly).
Allows checking for package name globally and adopt different code paths for each package.
Prerequisite for https://github.com/obsproject/obs-deps/pull/186 as caches generated by nightly runs are incompatible with that codebase otherwise.
This change adds new parameter `PackageName` to the build script which selects the kind of dependency package to build:
* `dependencies` (the default)
* `qt`
* `ffmpeg` (added later in https://github.com/obsproject/obs-deps/pull/186)
When the parameter is omitted, default Windows dependencies are built. If Qt is to be built `-PackageName qt` needs to be provided instead.
Needs to be tested on CI and later with #186 after merging and …
=> Update Windows build script to use explicit package names

Build-Dependencies.ps1
We accidentally left these out in a refactor.
Fixes a regression from 7d6ea5fcccc293156418c69c3c48a9761810867f (#200).
Don't want regressions.
Haven't tested locally. CI artifacts should show the difference.
=> Preserve Carla files in artifact

deps.ffmpeg/20-libpng.zsh, deps.ffmpeg/20-opus.zsh, deps.ffmpeg/30-libvorbis.zsh, deps.ffmpeg/40-aom.zsh
Fixed fixup step file path.
The scripts failed when I execute them.
Successfully built with WSL on my computer.
=> deps.ffmpeg: Fix fixup step error on windows

deps.ffmpeg/60-mbedtls.zsh
Fixes compilation errors of MbedTLS when compiling with Clang 15.
Clang 15 is the default compiler version on current macOS versions. The only reason this bug doesn't occur on CI is because the macOS 13 runners (and associated default Xcode version) are outdated.
Tested with Clang 15 on macOS 14.2.1.
=> deps.ffmpeg: Fix MbedTLS compile error with Clang 15

deps.macos/60-freetype.zsh
Fixes hard-coded path in Makefile by FreeType's build system to represent the manually created build directory for combined architectures.
Ensure that generated universal libraries are installed by generated Makefile and not just the architecture used as the base for the combined build directory.
Tested on macOS 14.1.2 and building universal architecture variant for FreeType2.
=> deps.macos: Fix installation of universal FreeType libraries

deps.ffmpeg/70-libdatachannel.ps1, deps.ffmpeg/70-libdatachannel.zsh
* Adds AV1, AAC and HEVC support
* Fixes https://github.com/obsproject/obs-studio/issues/9800
I have a working implementation [here](https://github.com/obsproject/obs-studio/pull/9331)
=> deps.ffmpeg, deps.windows: Update libdatachannel to v0.20.1

.github/actions/build-deps/action.yml, .github/actions/build-ffmpeg/action.yaml, .github/actions/build-qt/action.yaml, .github/actions/create-single-arch/action.yaml, .github/actions/create-universal/action.yaml, .github/actions/package-windows-qt/action.yaml, .github/workflows/main.yaml, .github/workflows/scheduled.yaml
CI: Update first-party GitHub Actions from v3 to v4
GitHub Actions has deprecated Actions based on node16. The v4 actions are based on node20. Replace first-party v3 actions with their v4 counterparts.
See:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Want to resolve deprecation warnings on CI. Want to avoid CI failing when the node16 actions are disabled.
Hasn't. CI will be the test.
=> CI: Update first-party GitHub Actions from v3 to v4

.github/workflows/scheduled.yaml
Add cache cleanup job as precondition for build jobs in scheduled workflow.
Avoids a possible race condition between cache cleanup and use of caches in the build jobs.
Also includes FFmpeg caches in the cleanup as the build action has been fully updated with expected scheduled cleanups.
Fixes cache save warnings emitted in scheduled FFmpeg build jobs due to original cache not being removed before its run.
Needs final test on CI.
=> CI: Fix cache refresh in scheduled nightly builds

deps.ffmpeg/40-x264.zsh, deps.ffmpeg/99-ffmpeg.zsh
Forces classic linker mode with AppleClang 15 on macOS.
Works around linker issues introduced by Xcode 15 beta 2 (tracked as FB13208302).
Tested locally on macOS 14.3.
=> deps.ffmpeg: Force classic linker for AppleClang 15.0.0+

.github/workflows/main.yaml, .github/workflows/scheduled.yaml
Updates macOS jobs to use macOS 14-based runners.
Enables macOS jobs to use environment similar to expected local build environments and makes use of the performance benefits of Apple Silicon-based hardware.
Needs final testing on CI.
=> CI: Update macOS jobs to use macOS 14 runners

deps.ffmpeg/40-aom.zsh
Enables AOM runtime CPU detection on macOS.
Runtime CPU detection in AOM has been extended to properly detect ARM64 CPUs and enable NEON features if possible - disabling the runtime detection has been found to lead to crashes when attempting to record using AOM on Apple Silicon Macs.
Fixes https://github.com/obsproject/obs-studio/issues/10226.
Tested on macOS 14.3.1 doing AOM recordings with an updated `libavcodec.dylib` inserted into OBS app bundle.
=> deps.ffmpeg: Enable runtime CPU detection for AOM to fix ARM64 crashes

.github/workflows/main.yaml, .github/workflows/scheduled.yaml
Force use of Xcode 15.2 in macOS-based runners.
Xcode 15.0.1 had a bug which lead to binaries crashing on macOS 12 or older when compiled with weak definitions (FB13097713).
Mainly exhibited by use of Qt in OBS Studio: https://bugreports.qt.io/browse/QTBUG-119848
Needs to be tested by building OBS with updated dependencies and generated version of OBS run on macOS 12 or macOS 11.
=> CI: Force use of Xcode 15.2 to fix runtime crashes on older macOS

deps.windows/80-wil.ps1, licenses/wil/LICENSE.txt
Add wil v1.0.240122.1 headers for win-mf.
Linked with PR: https://github.com/obsproject/obs-studio/pull/10471
Adds wil headers to be used with win-mf project in obs-studio.
Testing is described in the linked obs-studio PR.
- [ x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [ x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ x] My code is not on the master branch.
- [ x] The code has been tested.
- [ x] All commit messages are properly formatted and commits squashed where appropriate.
- [ x] I have included updates to all appropriate documentation.
=> deps.windows: Add WIL headers

deps.qt/checksums/qttools-everywhere-src-6.6.3.tar.xz.sha256, deps.qt/checksums/qttools-everywhere-src-6.6.3.zip.sha256, deps.qt/qt6.ps1, deps.qt/qt6.zsh
Build Qt Designer with our Qt deps 
We should have always have a readily available version of designer people can use without having to suffer through Qt's maintenance tool and download like 3 GB of Qt builds and/or Qt Creator which may or may not be built against an older Qt version.
Additionally this avoids issues where people use "whatever they had insatlled" which may not match the version OBS is using (on macOS/Windows at least) and make changes to the XML format that don't match the shipping version.
Should also help unblock https://github.com/obsproject/obs-studio/pull/10419
We'll see if we compile ey?
=> deps.qt: Add Qt Designer

deps.ffmpeg/70-librist.ps1
The year/ID component of the Visual Studio display name is not always the fourth token. As far as I can tell, it is always the last token, so we can just get that. This is what we do in Setup-Target.ps1.
See also:
* #174
* #178
I checked the syntax locally with a `$VisualStudioData` set to a copy of "Visual Studio Build Tools 2022", which is the known offender for the current syntax.
```
PS C:\> $VisualStudioData
InstanceId          : a63227f3
DisplayName         : Visual Studio Build Tools 2022
InstallationVersion : 17.10.35027.167
InstallationPath    : C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
InstallDate         : 5/30/2023 1:17:32 PM
PS C:\> ($VisualStudioData.DisplayName -split ' ')[3]
Tools
PS C:\> ($VisualStudioData.DisplayName -split ' ')[-1]
2022
```
I did …
=> deps.ffmpeg: Fix Visual Studio ID/version for librist

deps.macos/20-libajantv2.zsh
This change addresses some of the feedback provided to me by PatTheMav via Discord regarding the recently merged PR https://github.com/obsproject/obs-deps/pull/233.
I've updated the Mac libajantv2 build script to use the correct updated CMake variable args for the new libajantv2 repo. This change makes the CMake variable args consistent across all three supported platform build scripts (Win, Mac, Flatpak).
I've also added the ability to enable verbose CMake logging in the macOS libajantv2 script.
The libajantv2 build script CMake variable args were updated in the libajantv2 Windows and Flatpak scripts in the recent PR https://github.com/obsproject/obs-deps/pull/233 but accidentally left unchanged in the macOS script. This means that the macOS build leaves a bunch of unintended cruft in …
=> deps.macos: Fix incorrect CMake args and missing verbose logging in libajantv2 script

deps.macos/80-simde.zsh, deps.windows/60-simde.ps1, licenses/simde/CC0-1.0.txt, licenses/simde/COPYING
Add SIMD Everywhere to obs-deps
Reduce in-tree vendored deps in OBS Studio repo.
=> Add SIMD Everywhere

deps.ffmpeg/99-ffmpeg.ps1, deps.ffmpeg/99-ffmpeg.zsh
It was disabled to workaround issues with N editions of Windows.
Since a while FFmpeg is patched to dynamically load MFPlat.DLL rather than being directly linked to it, fixing the issues.
https://github.com/FFmpeg/FFmpeg/commit/1cb601ad10313981209a5918fc36a968068fc0ec
I fixed it a while ago, I had doubt it fixed it since mstorsjo added back `-lmfuuid` to fix building with MSVC.
But Rodney told me that it's a static library, so a non-issue.
I did not test to run OBS with this on Windows N.
=> deps.ffmpeg: Enable Media Foundation

deps.ffmpeg/70-nv-codec.ps1, deps.ffmpeg/70-nv-codec.zsh
Updates NVENC SDK to 12.2
Required for new SDK features (Ultra High Quality preset etc.) to work with https://github.com/obsproject/obs-studio/pull/10536
Replaced files locally to make sure it compiles.
=> deps.ffmpeg: Update nv-codec to 12.2.72.0

utils.pwsh/Invoke-SafeWebRequest.ps1
Note that there is a bug in curl that can prevent curl from successfully interpreting a fully downloaded file as completed. The bug was fixed on October 30, 2023 and is not yet available on curl included with Windows.
Fixed in curl 8.5.0.
https://github.com/curl/curl/commit/225db9196a71a19132a4c334f256b59854afc70c
I noticed that we have the Resume parameter, but that it wasn't implemented. I wanted to implement it to have a way to skip re-downloading a file that was already downloaded. SkipDeps skips build dependencies. SkipUnpack skips git checkouts and archive extraction but not downloads.
Alternatively, we could add something like SkipDownload and implement that, and remove the Resume parameter.
It may be important to note that due to us invoking MSYS2, the copy of curl from there can …
=> utils.pwsh: Add support for curl resume

.github/workflows/main.yaml
Due to recent changes to remove unnecessary x86 builds, the Qt x86 artifact no longer exists, so CI fails during release creation. Instead of assuming the file exists for all architectures, use a test and an if statement to check for possible matches.
Want to be able to make obs-deps releases.
It hasn't.
=> CI: Fix failure when trying to move Qt x86 zip

build-deps.zsh
Removes MbedTLS CMake package files for macOS FFmpeg builds.
Once the project switches MbedTLS 3.6+, there needs to be a way to distinguish between older and newer versions on the obs-studio side.
The path of least resistance is to use CMake package-based discovery for versions 3.6+ and find module-based discovery for older versions, which requires the older (current as of time of the commit) versions to not provide a CMake package as part of obs-deps.
> [!NOTE]
> Once MbedTLS is updated to version 3.6+, this removal will need to be removed again.
Tested removal on current `obs-deps` with an updated `obs-studio` to opportunistically use package discovery mode and observe automatic fallback to find module to discover MbedTLS as provided by current dependencies.
- Bug fix (non-breaking …
=> deps.ffmpeg: Remove MbedTLS CMake files from macOS FFmpeg package

.github/workflows/main.yaml
The previous fix attempt fixed the CI failure, but also didn't copy the necessary x64 files. Hopefully this corrects that.
Want a fully working obs-deps release.
Tested locally to see if the glob and loop worked. Has not been tested on CI.
=> CI: Fix x64 Qt files not being copied for release artifacts

.github/workflows/main.yaml
If no pattern match is found, which we expect for Qt x86 builds, then return an empty string by enabling the nullglob option.
Additionally, add quotes for paths for safety and fix the for loop array syntax.
To appease CI.
Test locally more thoroughly.
=> CI: Ensure finding no pattern match results in an empty string

deps.qt/qt6.ps1, deps.qt/qt6.zsh
Update download links for Qt 6.6.3 to unbreak scheduled nightly builds.
Qt 6.6 is considered a historical version of Qt 6 and has thus been archived and is not available from the official releases directory anymore.
Requires test run on CI.
=> deps.qt: Update Qt 6.6.3 download links to fix nightly builds

.github/workflows/main.yaml
Adds a wildcard to the end of the filenames to be uploaded in the final release for macOS artifacts.
In [releases](https://github.com/obsproject/obs-deps/releases/tag/2024-09-12), dSYMs for macOS dependencies are not being uploaded properly. Checksums are being generated, showing that the files are present. The Windows final deps upload paths include a wildcard at the end (to capture the `-PDBs` suffix), but this wildcard is not present for the macOS artifacts.
Tested on [local fork](https://github.com/jcm93/obs-deps/releases/tag/2024-12-23).
=> CI: Include dSYMs in release for macOS dependencies

.github/workflows/scheduled.yaml
Adds missing ARM64-specific configuration to the build matrix of the FFmpeg build step for Windows in the scheduled workflow.
Fix nightly builds.
Needs to be tested on CI itself.
=> CI: Fix missing arm64 configuration for scheduled Windows FFmpeg builds

deps.windows/40-detours.ps1, utils.pwsh/Setup-Host.ps1
Changes the DevShell arguments to explicitly include the host architecture whenever the `x86` architecture needs to be built on GitHub Actions runners.
While working without issue on local machines, it seems to be that the build scripts cannot correctly invoke a DevShell and the detours `nmake` build system for the x86 architecture without explicitly specifying the host architecture.
The same workaround breaks building other architecture on actual ARM64 Windows machines, thus it is now limited to CI runs only.
Tested locally in a Windows ARM64 VM, will be tested by CI for other architectures.
=> deps.windows: Fix architecture mismatch when building on ARM64 host

.Wingetfile, utils.pwsh/Install-BuildDependencies.ps1
Fix winget meson installation. Without this change, meson will not be installed automatically via winget. Can change the first commit prefix to `utils.pwsh` if preferred, since it also modifies a file there.
A second commit changes the syntax for `.Wingetfile` so that it is uniform for all entries.
Pointed out on #277. Further investigation showed that this does indeed fail if meson cannot be found with `Get-Command`.
Tested locally on Windows 11.
=> winget: Fix winget meson installation

deps.qt/qt6.zsh
Enable creation of separate debug information for all CMake configurations.
On macOS debug information is kept in the object files generated by the compiler and extracted into dSYM files using the reference information kept in the binaries.
Any binary built in debug information will not contain any debug information, instead the toolchain will find the information in the object files locally. Thus binaries created in debug configuration need to be shipped with their associated dSYM files if they are to be used on a different machine.
Tested with a Qt build with debug configuration, used on a separate computer and confirmed that debug information was correctly found when the associated dSYM files were loaded.
=> deps.qt: Enable creation of dSYM files for all configurations

deps.ffmpeg/80-amf.ps1, deps.ffmpeg/80-amf.zsh
- Update to full AMF 1.4.36
- This obs-deps PR is needed for: https://github.com/obsproject/obs-studio/pull/12098
- This AMF release contains the API for CQP support for B-frame AV1 encoding with AMD cards
- Tested on Navi31
=> deps.ffmpeg: Update to full AMF 1.4.36

utils.pwsh/Setup-Host.ps1
Updates the `msys2-keyring` before doing a full msys2 system update.
If the keyring is too outdated before an update is triggered, it seems that the public keys used to sign the updated packages are not considered valid by the local system and thus the update fails.
This attempts to update the keyring before doing the actual update.
Requires test runs on CI.
=> utils.pwsh: Force an update of the msys2 keyring before host update

deps.ffmpeg/60-mbedtls.ps1, deps.ffmpeg/60-mbedtls.zsh
Fix an issue where TLS/RTMPS connections would fail.
In OBS Studio 31.1.0, mbedTLS 3.6.2 causes RTMPS connections to fail. This was noticed by connections to Facebook Live failing.
Tested locally and this seems to fix streaming to Facebook Live.
=> deps.ffmpeg: Update mbedTLS to 3.6.4

utils.pwsh/Setup-Host.ps1
Remove the manual pacman keyring upgrade.
Effectively reverts:
* https://github.com/obsproject/obs-deps/pull/294
Partially reverts:
* https://github.com/obsproject/obs-deps/pull/292
The Windows 11 Arm runners do not have MSYS2 installed, and attempts to manually install it have failed. Installing via winget fails because winget is not available on the windows-2022 or windows-11-arm runners. Installing via chocolately fails because its install destination is non-standard, and their option to change the install destination is a paid option.
Just remove the manual pacman keyring upgrade for now.
Tested on my fork:
* https://github.com/RytoEX/obs-deps/actions/runs/17163679508/attempts/1
* https://github.com/RytoEX/obs-deps/actions/runs/17163679508
- Bug fix (non-breaking change which fixes an …
=> utils.pwsh: Remove manual pacman keyring upgrade
